#!/bin/sh

printf "Current Locale is $LANG\n\n"

echo "1 - Set Locale to ja_JP.UTF-8"
echo "2 - Set Locale to en_US.UTF-8"
while true; do
	read option
	case $option in
		[1]* ) localectl set-locale "LANG=ja_JP.UTF-8"; break;;
		[2]* ) localectl set-locale "LANG=en_US.UTF-8"; break;;
		* ) echo ""$option" is Invalid";
	esac
done

echo "Would you like to log out now? [y/N]"
read option
if [ `echo $option | tr [:upper:] [:lower:]` = y ]; then
	bspc quit
else
	echo "No Logout"
fi
