#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#3377bbbb'  # default
T='#eeFFeeee'  # text
W='#990000bb'  # wrong
V='#77ccffcc'  # verifying

i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T       \
--wrongcolor=$T       \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--keylayout 0         \
\
--veriftext="Hashing..." \
--wrongtext="Mismatch"   \
#--textsize=20
#--modsize=10
#--timefont=mono
#--datefont=sierf
