#!/bin/bash

genqr() {
	mkdir -p /tmp/qrencode
	now=$(date +"%Y_%m_%d_%k-%M-%S")
	img="Nepcode_$now.png"
	cd /tmp/qrencode && qrencode -s 10 -o "$img" "$url"
	sxiv "$img"
}

notify_send() {
	files=$(shuf -n1 -e /home/nep/Pictures/Gyate\ Gyate\ Kao/Gabriel\ Dropout/*)
	notify-send --expire-time=2000 -i view-fullscreen "$msg" --icon="$files"  && sleep 0.5
}

main() {
	case "$1" in
		"")
			msg="No Input!"
			notify_send
			;;
		*)
			url="$1"
			msg="終わりました!"
			notify_send
			genqr
		esac
}

main "$@"
