#!/bin/bash

_rofi() {
	rofi -sep '|' -columns 6 -lines 1 -disable-history true -cycle true \
		-width 80 -height 200 -xoffset 0 -yoffset 0 \
		-dmenu -p "$PROMPT"
	}

PROMPT="Session Menu"
CHOICE=$(echo "Lock|Sleep|Suspend|Logout|Reboot|Shutdown" | _rofi)

case "$CHOICE" in
	Lock)
		lockscript
		;;
	Sleep)
		lockscript && systemctl hibernate
		;;
	Suspend)
		lockscript && systemctl suspend
		;;
	Logout)
		PROMPT="Are you Sure?"
		CHOICE=$(echo "No|Yes" | _rofi)
		case "$CHOICE" in
			Yes)
				pkill "$DISPLAY_SESSION"
				;;
		esac
		;;

	Reboot)
		PROMPT="Are you Sure?"
		CHOICE=$(echo "No|Yes" | _rofi)
		case "$CHOICE" in
			Yes)
				systemctl reboot
				;;
		esac
		;;
	Shutdown)
		PROMPT="Are you Sure?"
		CHOICE=$(echo "No|Yes" | _rofi)
		case "$CHOICE" in
			Yes)
				systemctl poweroff
				;;
		esac
		;;
esac
