#!/bin/sh

capture() {
	mkdir -p ~/Pictures/Captures/
	maim $1 -m 10 | tee ~/Pictures/Captures/Neptop_$(date +%Y_%m_%d_%N).png | xclip -selection clipboard -t image/png
}

notify_send() {
	icon=$(shuf -n1 -e ~/Pictures/Gyate\ Gyate\ Kao/Gabriel\ Dropout/*)
	notify-send --expire-time=2000 -i view-fullscreen 'Cheese!~' 'Saved to ~/Pictures/Captured' --icon="$icon"
}

main() {
	case "$1" in
		window)
			capture "-i $(xdotool getactivewindow)"
			notify_send
			;;
		crop)
			capture -s
			notify_send
			;;
		*)
			capture
			notify_send
	esac
}

main "$@"
