#!/bin/sh

capture() {
	mkdir -p ~/Pictures/Captures/
	cd ~/Pictures/Captures/ && scrot 'Neptop_%Y_%m_%d_%H-%M-%S_$wx$h.png' -q 100 $1 -e 'xclip -se c -t image/png -i "$f"'
}

notify_send() {
	icon=$(shuf -n1 -e ~/Pictures/Gyate\ Gyate\ Kao/Gabriel\ Dropout/*)
	notify-send --expire-time=2000 -i view-fullscreen 'Cheese!~' 'Saved to ~/Pictures/Captured' --icon="$icon"
}

main() {
	case "$1" in
		window)
			capture -u
			notify_send
			;;
		crop)
			capture -s
			notify_send
			;;
		*)
			capture
			notify_send
	esac
}

main "$@"
